
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineFortranCompiler.cmake:190 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the Fortran compiler identification source file "CMakeFortranCompilerId.F" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      Microsoft Visual Studio 2022 Version 17.10.5.
      Copyright (C) Microsoft Corp. All rights reserved.
      Build started at 19:49...
      1>------ Build started: Project: CompilerIdFortran, Configuration: Debug x64 ------
      Compiling with Intel® Fortran Compiler Classic 2021.12.0 [Intel(R) 64]...
      CMakeFortranCompilerId.F
      Intel(R) Fortran Intel(R) 64 Compiler Classic for applications running on Intel(R) 64, Version 2021.13.0 Build 20240602_000000
      Copyright (C) 1985-2024 Intel Corporation.  All rights reserved.
      ifort: remark #10448: Intel(R) Fortran Compiler Classic (ifort) is now deprecated and will be discontinued late 2024. Intel recommends that customers transition now to using the LLVM-based Intel(R) Fortran Compiler (ifx) for continued Windows* and Linux* support, new language support, new language features, and optimizations. Use '/Qdiag-disable:10448' to disable this message.
      Linking...
      Link: executing 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.40.33807\\bin\\HostX64\\x64\\link.exe'
      Microsoft (R) Incremental Linker Version 14.40.33813.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
      /OUT:.\\CompilerIdFortran.exe
      /INCREMENTAL:NO
      /MANIFEST
      /MANIFESTFILE:Debug\\CompilerIdFortran.exe.intermediate.manifest
      "/MANIFESTUAC:level='asInvoker' uiAccess='false'"
      /DEBUG
      /PDB:C:\\Users\\louis\\Documents\\GitHub\\chiralpl\\CMakeFiles\\3.31.0-rc2\\CompilerIdFortran\\CompilerIdFortran.pdb
      /SUBSYSTEM:CONSOLE
      /IMPLIB:C:\\Users\\louis\\Documents\\GitHub\\chiralpl\\CMakeFiles\\3.31.0-rc2\\CompilerIdFortran\\CompilerIdFortran.lib
      Debug\\CMakeFortranCompilerId.obj
      Embedding manifest...
      Performing Post-Build Event...
      CMAKE_Fortran_COMPILER=C:\\Program Files (x86)\\Intel\\oneAPI\\compiler\\2024.2\\bin\\ifort.exe
      
      Build log written to  "file://C:/Users/louis/Documents/GitHub/chiralpl/CMakeFiles/3.31.0-rc2/CompilerIdFortran/Debug/BuildLog.htm"
      CompilerIdFortran - 0 error(s), 0 warning(s)
      ========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
      ========== Build completed at 19:49 and took 01.775 seconds ==========
      
      
      Compilation of the Fortran compiler identification source "CMakeFortranCompilerId.F" produced "CompilerIdFortran.exe"
      
      Compilation of the Fortran compiler identification source "CMakeFortranCompilerId.F" produced "CompilerIdFortran.pdb"
      
      Compilation of the Fortran compiler identification source "CMakeFortranCompilerId.F" produced "CompilerIdFortran.vfproj"
      
      The Fortran compiler identification is Intel, found in:
        C:/Users/louis/Documents/GitHub/chiralpl/CMakeFiles/3.31.0-rc2/CompilerIdFortran/CompilerIdFortran.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerABI.cmake:74 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeTestFortranCompiler.cmake:20 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting Fortran compiler ABI info"
    directories:
      source: "C:/Users/louis/Documents/GitHub/chiralpl/CMakeFiles/CMakeScratch/TryCompile-o0w65b"
      binary: "C:/Users/louis/Documents/GitHub/chiralpl/CMakeFiles/CMakeScratch/TryCompile-o0w65b"
    cmakeVariables:
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
      CMAKE_Fortran_FLAGS: "/W1 /nologo /fpp /libs:dll /threads"
      CMAKE_Fortran_FLAGS_DEBUG: "/Od /debug:full /dbglibs"
    buildResult:
      variable: "CMAKE_Fortran_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/louis/Documents/GitHub/chiralpl/CMakeFiles/CMakeScratch/TryCompile-o0w65b'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/devenv.com" CMAKE_TRY_COMPILE.sln /build Debug /project cmTC_1bf4a
        
        Microsoft Visual Studio 2022 Version 17.10.5.
        Copyright (C) Microsoft Corp. All rights reserved.
        Build started at 19:49...
        1>------ Build started: Project: cmTC_1bf4a, Configuration: Debug x64 ------
        Compiling with Intel® Fortran Compiler Classic 2021.12.0 [Intel(R) 64]...
        CMakeFortranCompilerABI.F90
        ifort: remark #10448: Intel(R) Fortran Compiler Classic (ifort) is now deprecated and will be discontinued late 2024. Intel recommends that customers transition now to using the LLVM-based Intel(R) Fortran Compiler (ifx) for continued Windows* and Linux* support, new language support, new language features, and optimizations. Use '/Qdiag-disable:10448' to disable this message.
        Compiling manifest to resources...
        Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384
        Copyright (C) Microsoft Corporation.  All rights reserved.
        Linking...
        Link: executing 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.40.33807\\bin\\HostX64\\x64\\link.exe'
        Microsoft (R) Incremental Linker Version 14.40.33813.0
        Copyright (C) Microsoft Corporation.  All rights reserved.
        /OUT:C:\\Users\\louis\\Documents\\GitHub\\chiralpl\\CMakeFiles\\CMakeScratch\\TryCompile-o0w65b\\Debug\\cmTC_1bf4a.exe
        /VERSION:0.0
        /MANIFEST
        /MANIFESTFILE:cmTC_1bf4a.dir\\Debug\\cmTC_1bf4a.exe.intermediate.manifest
        "/MANIFESTUAC:level='asInvoker' uiAccess='false'"
        /DEBUG
        /PDB:C:\\Users\\louis\\Documents\\GitHub\\chiralpl\\CMakeFiles\\CMakeScratch\\TryCompile-o0w65b\\Debug/cmTC_1bf4a.pdb
        /SUBSYSTEM:CONSOLE
        /IMPLIB:C:\\Users\\louis\\Documents\\GitHub\\chiralpl\\CMakeFiles\\CMakeScratch\\TryCompile-o0w65b\\Debug\\cmTC_1bf4a.lib
        /machine:x64
        /debug
        /INCREMENTAL
        cmTC_1bf4a.dir\\Debug\\CMakeFortranCompilerABI.obj
        cmTC_1bf4a.dir\\Debug\\cmTC_1bf4a.exe.embed.manifest.res
        Embedding manifest...
        Microsoft (R) Manifest Tool
        Copyright (c) Microsoft Corporation.
        All rights reserved.
        
        Build log written to  "file://C:/Users/louis/Documents/GitHub/chiralpl/CMakeFiles/CMakeScratch/TryCompile-o0w65b/cmTC_1bf4a.dir/Debug/BuildLog.htm"
        cmTC_1bf4a - 0 error(s), 0 warning(s)
        ========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
        ========== Build completed at 19:49 and took 00.972 seconds ==========
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerABI.cmake:218 (message)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeTestFortranCompiler.cmake:20 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Parsed Fortran implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?))("|,| |$)]
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerABI.cmake:227 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeTestFortranCompiler.cmake:20 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Determine Intel Fortran Compiler Implicit Link Path"
    directories:
      source: "C:/Program Files/CMake/share/cmake-3.31/Modules/IntelVSImplicitPath"
      binary: "C:/Users/louis/Documents/GitHub/chiralpl/CMakeFiles/IntelVSImplicitPath"
    buildResult:
      variable: "IFORT_LIB_PATH_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/louis/Documents/GitHub/chiralpl/CMakeFiles/IntelVSImplicitPath'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/devenv.com" IntelFortranImplicit.sln /build Debug /project ALL_BUILD
        
        Microsoft Visual Studio 2022 Version 17.10.5.
        Copyright (C) Microsoft Corp. All rights reserved.
        Build started at 19:49...
        1>------ Build started: Project: ZERO_CHECK, Configuration: Debug x64 ------
        1>1>Checking Build System
        2>------ Build started: Project: FortranLib, Configuration: Debug x64 ------
        Generating output.cmake
        Compiling with Intel® Fortran Compiler Classic 2021.12.0 [Intel(R) 64]...
        hello.f
        ifort: remark #10448: Intel(R) Fortran Compiler Classic (ifort) is now deprecated and will be discontinued late 2024. Intel recommends that customers transition now to using the LLVM-based Intel(R) Fortran Compiler (ifx) for continued Windows* and Linux* support, new language support, new language features, and optimizations. Use '/Qdiag-disable:10448' to disable this message.
        Creating library...
        
        Build log written to  "file://C:/Users/louis/Documents/GitHub/chiralpl/CMakeFiles/IntelVSImplicitPath/FortranLib.dir/Debug/BuildLog.htm"
        FortranLib - 0 error(s), 0 warning(s)
        3>------ Build started: Project: ALL_BUILD, Configuration: Debug x64 ------
        3>Building Custom Rule C:/Program Files/CMake/share/cmake-3.31/Modules/IntelVSImplicitPath/CMakeLists.txt
        ========== Build: 3 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
        ========== Build completed at 19:49 and took 01.908 seconds ==========
        
      exitCode: 0
...
